//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrateBots.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrateBots.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 I can&apos;t understand what you just said. Please try again. 的本地化字符串。
        /// </summary>
        internal static string RootDialog_Chat_Error {
            get {
                return ResourceManager.GetString("RootDialog_Chat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keaton 的本地化字符串。
        /// </summary>
        internal static string RootDialog_clientA {
            get {
                return ResourceManager.GetString("RootDialog_clientA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ingrid 的本地化字符串。
        /// </summary>
        internal static string RootDialog_clientB {
            get {
                return ResourceManager.GetString("RootDialog_clientB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leo 的本地化字符串。
        /// </summary>
        internal static string RootDialog_clientC {
            get {
                return ResourceManager.GetString("RootDialog_clientC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 buy 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HOME_buy {
            get {
                return ResourceManager.GetString("RootDialog_HOME_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HOME_buy_NO {
            get {
                return ResourceManager.GetString("RootDialog_HOME_buy_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sure 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HOME_buy_Q1 {
            get {
                return ResourceManager.GetString("RootDialog_HOME_buy_Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Markham 的本地化字符串。
        /// </summary>
        internal static string RootDialog_House_Markham {
            get {
                return ResourceManager.GetString("RootDialog_House_Markham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Branch 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HOUSElist_branch {
            get {
                return ResourceManager.GetString("RootDialog_HOUSElist_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 budget 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HOUSElist_budget {
            get {
                return ResourceManager.GetString("RootDialog_HOUSElist_budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 learn 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HOUSElist_learn {
            get {
                return ResourceManager.GetString("RootDialog_HOUSElist_learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 located 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HOUSElist_located {
            get {
                return ResourceManager.GetString("RootDialog_HOUSElist_located", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mortgage 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HOUSElist_mortgage {
            get {
                return ResourceManager.GetString("RootDialog_HOUSElist_mortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 process 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HOUSElist_process {
            get {
                return ResourceManager.GetString("RootDialog_HOUSElist_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yes 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HOUSElist_yes {
            get {
                return ResourceManager.GetString("RootDialog_HOUSElist_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 homep 的本地化字符串。
        /// </summary>
        internal static string RootDialog_HP_calc {
            get {
                return ResourceManager.GetString("RootDialog_HP_calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 affect 的本地化字符串。
        /// </summary>
        internal static string RootDialog_Keaton_affect {
            get {
                return ResourceManager.GetString("RootDialog_Keaton_affect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 current balance 的本地化字符串。
        /// </summary>
        internal static string RootDialog_Keaton_currentBalance {
            get {
                return ResourceManager.GetString("RootDialog_Keaton_currentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 disabled 的本地化字符串。
        /// </summary>
        internal static string RootDialog_Keaton_disabled {
            get {
                return ResourceManager.GetString("RootDialog_Keaton_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keaton 的本地化字符串。
        /// </summary>
        internal static string RootDialog_Keaton_name {
            get {
                return ResourceManager.GetString("RootDialog_Keaton_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 protect 的本地化字符串。
        /// </summary>
        internal static string RootDialog_Keaton_protect {
            get {
                return ResourceManager.GetString("RootDialog_Keaton_protect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sign 的本地化字符串。
        /// </summary>
        internal static string RootDialog_Keaton_sign {
            get {
                return ResourceManager.GetString("RootDialog_Keaton_sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 important 的本地化字符串。
        /// </summary>
        internal static string RootDialog_Leo_important {
            get {
                return ResourceManager.GetString("RootDialog_Leo_important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 why 的本地化字符串。
        /// </summary>
        internal static string RootDialog_Leo_why {
            get {
                return ResourceManager.GetString("RootDialog_Leo_why", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello! My name is James Bot, how should I address you? 的本地化字符串。
        /// </summary>
        internal static string RootDialog_Welcome_Message {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Message", resourceCulture);
            }
        }
    }
}
